# Please make sure to update the license_key information with the
# license key for your New Relic account.
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'YOUR_LICENSE_KEY_HERE'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  verbose: 1
#
# Agent Configuration:
#
agents:
  # AWS CloudWatch configuration.
  aws_cloudwatch:
    # Update with you AWS account keys:
    access_key: 'YOUR_AWS_ACCESS_KEY'
    secret_key: 'YOUR_AWS_SECRET_KEY'
    # Update with your AWS region (currently only support one per agent).
    region: 'us-east-1'
